### ISSUE TITLE
Build/Compile libjpeg-turbo

### ISSUE THREAD

**Issue by antoniojmabreu** [YonghaoHe/LFD-A-Light-and-Fast-Detector#22]
Win10-x64, powershell

I'm trying to use WIDERFACE predict.py, but i have the following error:

ImportError: cannot import name 'nms_ext' from 'lfd.model.utils.libs'

I think this is because of libjpeg-turbo.

Can anyone help me on how to build and compile libjpeg-turbo on windows?

**Comment by YonghaoHe** [comment]
@antoniojmabreu I think you can get what you want by google easily.

**Comment by antoniojmabreu** [comment]
I followed all the steps to build and compile libjpeg-turbo but i get the following error.

(env) PS G:\OneDrive - Universidade da Beira Interior\EI\Mestrado\1 ano\2 semestre\IC\Projeto\LFD-A-Light-and-Fast-Detector-master\WIDERFACE_train> python.exe .\predict.py
Traceback (most recent call last):
  File ".\predict.py", line 4, in <module>
    from lfd.data_pipeline.augmentation import *
  File "G:\OneDrive - Universidade da Beira Interior\EI\Mestrado\1 ano\2 semestre\IC\Projeto\LFD-A-Light-and-Fast-Detector-master\WIDERFACE_train\lfd\data_pipeline\__init__.py", line 4, in <module>
    from .data_loader import *
  File "G:\OneDrive - Universidade da Beira Interior\EI\Mestrado\1 ano\2 semestre\IC\Projeto\LFD-A-Light-and-Fast-Detector-master\WIDERFACE_train\lfd\data_pipeline\data_loader\__init__.py", line 3, in <module>
    from .data_loader import DataLoader
  File "G:\OneDrive - Universidade da Beira Interior\EI\Mestrado\1 ano\2 semestre\IC\Projeto\LFD-A-Light-and-Fast-Detector-master\WIDERFACE_train\lfd\data_pipeline\data_loader\data_loader.py", line 8, in <module>
    from ..dataset import turbojpeg, reserved_keys
  File "G:\OneDrive - Universidade da Beira Interior\EI\Mestrado\1 ano\2 semestre\IC\Projeto\LFD-A-Light-and-Fast-Detector-master\WIDERFACE_train\lfd\data_pipeline\dataset\__init__.py", line 7, in <module>
    from .utils import *
  File "G:\OneDrive - Universidade da Beira Interior\EI\Mestrado\1 ano\2 semestre\IC\Projeto\LFD-A-Light-and-Fast-Detector-master\WIDERFACE_train\lfd\data_pipeline\dataset\utils\__init__.py", line 3, in <module>
    from .turbojpeg import turbojpeg
  File "G:\OneDrive - Universidade da Beira Interior\EI\Mestrado\1 ano\2 semestre\IC\Projeto\LFD-A-Light-and-Fast-Detector-master\WIDERFACE_train\lfd\data_pipeline\dataset\utils\turbojpeg.py", line 456, in <module>
    turbojpeg = TurboJPEG(lib_path=target_libturbojpeg_path)
  File "G:\OneDrive - Universidade da Beira Interior\EI\Mestrado\1 ano\2 semestre\IC\Projeto\LFD-A-Light-and-Fast-Detector-master\WIDERFACE_train\lfd\data_pipeline\dataset\utils\turbojpeg.py", line 153, in __init__
    self.__find_turbojpeg() if lib_path is None else lib_path)
  File "C:\Users\anton\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\anton\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

Can you help me please?
Do I need to change some setings to run the code on a Windows machine?
Thanks in advance.

**Comment by Tetsujinfr** [comment]
Did you compile turbo libjpeg from source or did you install binaries directly?
Btw you wrote you are on Win10 x64 but the error msg you copy/pasted indicates you are trying to run the code on a 32bit Windows machine. Confusing. you need to provide more details if want some help

**Comment by antoniojmabreu** [comment]
I tryed both compiling libjpeg with Visual Studio and instaling the binaries directly but the error is the same.
I'm on a x64bit windows 10 machine, python 3.6.8 (64bit).

**Comment by Tetsujinfr** [comment]
can you share your CMakeLists.txt ?
can you share the output of cmake .. also?

**Comment by YonghaoHe** [comment]
@antoniojmabreu maybe you can visit [website](https://sourceforge.net/projects/libjpeg-turbo/files/2.0.5/), and choose the appropriate item (libjpeg-turbo-2.0.5-vc64.exe, libjpeg-turbo-2.0.5-vc.exe). These two items are built binaries. Alternatively, you can compile from source code by carefully reading the instructions.
